---
- name: NTP Restart Redhat
  service: name=ntpd state=restarted
  when: ansible_os_family == "RedHat"

- name: NTP Restart Debian
  service: name=ntp state=restarted
  when: ansible_os_family == "Debian"
